version: 0.2

phases:
  install:
    commands:
      - cd infrastructure
      - npm install -g yarn
      - yarn global add aws-cdk
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn synth

artifacts:
  files:
    - infrastructure/synth/*
  discard-paths: yes