version: 0.2

phases:
  install:
    commands:
      - cd infrastructure
      - sudo apt-get update -y && sudo apt-get install -y yarn
      - yarn global add aws-cdk
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn synth

artifacts:
  files:
    - infrastructure/synth/*
  discard-paths: yes